version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: >-
    ./build.ps1 Dist -Configuration Debug

    7z a binaries_debug.zip %APPVEYOR_BUILD_FOLDER%\dist\*
test: off
artifacts:
- path: binaries_debug.zip
  name: netspherepirates
deploy: off
